# config/database.yml

default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 
  host: localhost

development:
  <<: *default
  database: ticketing-event-ms

test:
  <<: *default
  database: ticketing-event-ms

production:
  <<: *default
  database: ticketing-event-ms
  username: your_mysql_production_username
  password: your_mysql_production_password
  host: your_mysql_production_host
